### ISSUE TITLE
로그인: 자체 로그인 구현

### ISSUE THREAD

**Issue by cw-y** [CareKids/backend#3]
# Description
로그인 中 자체 로그인 구현

# TODO
- [ ] SecurityConfig 설정
- [ ] DTO, DAO 설정
- [ ] URL 매핑
- [ ] 타임리프 작성 + 테스트
- [ ] 예외처리

# ETC
- [ ] API 문서 작성
