### ISSUE TITLE
주말 어린이집 API 구현

### ISSUE THREAD

**Issue by cw-y** [CareKids/backend#9]
# Description
주말 어린이집 기능 구현

# TODO
- [x] 로그인 전 리스트 조회 (페이징)
- [x] 로그인 후 리스트 조회 (페이징)
- [x] 현재 운영 중인 곳만 보여주기
- [x] 동적 쿼리: 지역 필터 검색

# ETC
- [x] API 문서 작성
